#!/usr/bin/env python3
"""Generate language bindings for the NoxCue SDK wire contract."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONTRACT = ROOT / "packages" / "sdk-contract" / "contract.json"
PYTHON_OUTPUT = ROOT / "packages" / "python-sdk" / "src" / "noxcue" / "_contract.py"
TYPESCRIPT_OUTPUT = ROOT / "packages" / "sdk" / "src" / "contract.ts"


def python_source(contract: dict[str, object]) -> str:
    def literal(name: str, value: object) -> str:
        return f"{name} = {value!r}\n"

    limits = contract["limits"]
    assert isinstance(limits, dict)
    return (
        """# Generated by scripts/generate-sdk-contract.py. Do not edit.\n\n"""
        + "".join(
            [
                literal("CONTRACT_VERSION", contract["contractVersion"]),
                literal("SDK_VERSION", contract["sdkVersion"]),
                literal("__version__", contract["sdkVersion"]),
                literal("DEFAULT_ENDPOINT", contract["defaultEndpoint"]),
                literal("AUTH_FEATURES", tuple(contract["authFeatures"])),
                literal("ENVIRONMENTS", tuple(contract["environments"])),
                literal("OUTCOMES", tuple(contract["outcomes"])),
                literal("REASONS", tuple(contract["reasons"])),
                literal("DELIVERY_ERRORS", tuple(contract["deliveryErrors"])),
                literal("DEFAULT_TIMEOUT_MS", limits["defaultTimeoutMs"]),
                literal("MAX_TIMEOUT_MS", limits["maxTimeoutMs"]),
                literal("MAX_BODY_BYTES", limits["maxBodyBytes"]),
                literal("MAX_RESPONSE_BYTES", limits["maxResponseBytes"]),
                literal("RETRY_DELAY_MS", limits["retryDelayMs"]),
                literal("MAX_RETRY_AFTER_MS", limits["maxRetryAfterMs"]),
            ]
        )
    )


def typescript_source(contract: dict[str, object]) -> str:
    limits = contract["limits"]
    assert isinstance(limits, dict)

    def value(name: str, item: object) -> str:
        return f"export const {name} = {json.dumps(item, separators=(',', ':'))} as const;\n"

    return (
        "// Generated by scripts/generate-sdk-contract.py. Do not edit.\n\n"
        + "".join(
            [
                value("CONTRACT_VERSION", contract["contractVersion"]),
                value("SDK_VERSION", contract["sdkVersion"]),
                value("DEFAULT_ENDPOINT", contract["defaultEndpoint"]),
                value("NOXCUE_AUTH_FEATURES", contract["authFeatures"]),
                value("NOXCUE_ENVIRONMENTS", contract["environments"]),
                value("NOXCUE_OUTCOMES", contract["outcomes"]),
                value("NOXCUE_REASONS", contract["reasons"]),
                value("DELIVERY_ERRORS", contract["deliveryErrors"]),
                value("DEFAULT_TIMEOUT_MS", limits["defaultTimeoutMs"]),
                value("MAX_TIMEOUT_MS", limits["maxTimeoutMs"]),
                value("MAX_BODY_BYTES", limits["maxBodyBytes"]),
                value("MAX_RESPONSE_BYTES", limits["maxResponseBytes"]),
                value("RETRY_DELAY_MS", limits["retryDelayMs"]),
                value("MAX_RETRY_AFTER_MS", limits["maxRetryAfterMs"]),
            ]
        )
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    contract = json.loads(CONTRACT.read_text())
    typescript_package = json.loads(
        (ROOT / "packages" / "sdk" / "package.json").read_text()
    )
    if typescript_package["version"] != contract["sdkVersion"]:
        print("packages/sdk/package.json version must equal contract.json sdkVersion")
        return 1
    outputs = {
        PYTHON_OUTPUT: python_source(contract),
        TYPESCRIPT_OUTPUT: typescript_source(contract),
    }
    if args.check:
        stale = []
        for output, expected in outputs.items():
            actual = output.read_text() if output.exists() else ""
            if actual != expected:
                stale.append(str(output.relative_to(ROOT)))
        if stale:
            print(f"{', '.join(stale)} stale; run scripts/generate-sdk-contract.py")
            return 1
        return 0
    for output, expected in outputs.items():
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(expected)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
