import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { deleteRawJson, getRawJson, postRawJson, putRawJson } from "../../api/http";
import { useConfirmDialog } from "../../components/ConfirmDialog";

type CueKey = { id: string; name: string; kind: "publishable" | "secret"; prefix: string; lastUsedAt: string | null; revokedAt: string | null };
type CueSource = { id: string; name: string; environment: string; enabled: boolean; keys: CueKey[]; lastActivityAt: string | null };
type SourcesResponse = { sources?: CueSource[] };
type KeyResponse = { key: CueKey & { value: string }; warning: string };

export function NoxCueSources({ organizationId, projectId, isAdmin }: { organizationId: string; projectId: string; isAdmin: boolean }) {
  const { confirm, confirmation } = useConfirmDialog();
  const scope = { organizationId, projectId };
  const queryClient = useQueryClient();
  const [name, setName] = useState("");
  const [environment, setEnvironment] = useState("production");
  const [secret, setSecret] = useState<string | null>(null);
  const key = ["cue", organizationId, projectId, "sources"];
  const query = useQuery({ queryKey: key, queryFn: ({ signal }) => getRawJson("/api/v1/cues/sources", signal, scope) as Promise<SourcesResponse> });
  const refresh = () => queryClient.invalidateQueries({ queryKey: key });
  const create = useMutation({ mutationFn: () => postRawJson("/api/v1/cues/sources", { name: name.trim(), environment, projectId }, scope), onSuccess: () => { setName(""); void refresh(); } });
  const remove = useMutation({ mutationFn: (sourceId: string) => deleteRawJson(`/api/v1/cues/sources/${encodeURIComponent(sourceId)}`, scope), onSuccess: () => void refresh() });
  const createKey = useMutation({ mutationFn: ({ sourceId, kind }: { sourceId: string; kind: "publishable" | "secret" }) => postRawJson<KeyResponse>(`/api/v1/cues/sources/${encodeURIComponent(sourceId)}/keys`, { name: kind === "publishable" ? "Browser ingest" : "Server ingest", kind }, scope), onSuccess: (result) => { setSecret(result.key.value); void refresh(); } });
  const rotate = useMutation({ mutationFn: ({ sourceId, keyId }: { sourceId: string; keyId: string }) => postRawJson<KeyResponse>(`/api/v1/cues/sources/${encodeURIComponent(sourceId)}/keys/${encodeURIComponent(keyId)}/rotate`, {}, scope), onSuccess: (result) => { setSecret(result.key.value); void refresh(); } });
  const revoke = useMutation({ mutationFn: ({ sourceId, keyId }: { sourceId: string; keyId: string }) => deleteRawJson(`/api/v1/cues/sources/${encodeURIComponent(sourceId)}/keys/${encodeURIComponent(keyId)}`, scope), onSuccess: () => void refresh() });
  return <div className="workspace-view cue-sources">
    {secret ? <section className="secret-once"><b>Copy this ingest key now</b><p>It cannot be recovered after you close this message.</p><div><code>{secret}</code><button className="button" onClick={() => void navigator.clipboard.writeText(secret)}>Copy</button></div><button className="mini-button" onClick={() => setSecret(null)}>I stored it securely</button></section> : null}
    {isAdmin ? <form className="settings-card cue-source-create" onSubmit={(event) => { event.preventDefault(); create.mutate(); }}><header><div><b>Add telemetry source</b><p>Keep each product and environment isolated with its own ingest key.</p></div></header><div className="settings-form-grid"><label>Source name<input value={name} maxLength={120} onChange={(event) => setName(event.target.value)} placeholder="N1 App" /></label><label>Environment<select value={environment} onChange={(event) => setEnvironment(event.target.value)}><option value="production">Production</option><option value="staging">Staging</option><option value="development">Development</option><option value="preview">Preview</option><option value="test">Test</option><option value="local">Local</option></select></label></div><button className="button primary-button" disabled={!name.trim() || create.isPending}>{create.isPending ? "Creating…" : "Create source"}</button>{create.error ? <small role="alert">{create.error.message}</small> : null}</form> : null}
    {query.isLoading ? <p>Loading sources…</p> : query.isError ? <p role="alert">Could not load telemetry sources.</p> : (query.data?.sources ?? []).length ? <div className="cue-source-list">{(query.data?.sources ?? []).map((source) => <section className="settings-card" key={source.id}><header><div><b>{source.name}</b><p>{source.environment} · {source.enabled ? "ingest enabled" : "ingest disabled"}{source.lastActivityAt ? ` · last activity ${new Date(source.lastActivityAt).toLocaleString()}` : ""}</p></div>{isAdmin ? <button type="button" className="mini-button destructive" disabled={remove.isPending} onClick={() => void confirm({ title: "Delete telemetry source?", detail: `${source.name} and all of its ingest keys will be permanently removed.`, confirmLabel: "Delete source", destructive: true }).then((confirmed) => { if (confirmed) remove.mutate(source.id); })}>Delete</button> : null}</header><div className="list-surface">{source.keys.filter((item) => !item.revokedAt).map((item) => <div className="list-row" key={item.id}><span className="row-symbol">K</span><span className="list-copy"><b>{item.name}</b><small><code>{item.prefix}…</code> · {item.kind}{item.lastUsedAt ? ` · used ${new Date(item.lastUsedAt).toLocaleString()}` : " · unused"}</small></span>{isAdmin ? <span className="list-meta"><button className="mini-button" onClick={() => rotate.mutate({ sourceId: source.id, keyId: item.id })}>Rotate</button><button className="mini-button destructive" onClick={() => void confirm({ title: "Revoke ingest key?", detail: `${item.name} will stop accepting events immediately.`, confirmLabel: "Revoke key", destructive: true }).then((confirmed) => { if (confirmed) revoke.mutate({ sourceId: source.id, keyId: item.id }); })}>Revoke</button></span> : null}</div>)}{!source.keys.some((item) => !item.revokedAt) ? <p className="feed-empty-group">No active keys.</p> : null}</div>{isAdmin ? <div className="maintenance-actions"><button className="button" onClick={() => createKey.mutate({ sourceId: source.id, kind: "secret" })}>Create server key</button><button className="button" onClick={() => createKey.mutate({ sourceId: source.id, kind: "publishable" })}>Create browser key</button></div> : null}<CueCardEditor sourceId={source.id} scope={scope} isAdmin={isAdmin} /></section>)}</div> : <div className="empty-view"><h2>No telemetry sources</h2><p>Create a source before sending NoxCue events.</p></div>}
    {confirmation}
  </div>;
}

type CueCard = { metricKey: string; enabled: boolean; dailyLabel: string | null; cumulativeLabel: string | null; perActiveEnabled: boolean };

function CueCardEditor({ sourceId, scope, isAdmin }: { sourceId: string; scope: { organizationId: string; projectId: string }; isAdmin: boolean }) {
  const query = useQuery({ queryKey: ["cue-cards", sourceId], queryFn: ({ signal }) => getRawJson(`/api/v1/cues/sources/${encodeURIComponent(sourceId)}/cards`, signal, scope) as Promise<{ cards?: CueCard[] }> });
  if (query.isLoading) return <p>Loading report cards…</p>;
  if (query.isError) return <small role="alert">Report cards could not be loaded.</small>;
  return <CueCardForm key={JSON.stringify(query.data?.cards ?? [])} sourceId={sourceId} scope={scope} initial={query.data?.cards ?? []} isAdmin={isAdmin} onSaved={() => query.refetch()} />;
}

function CueCardForm({ sourceId, scope, initial, isAdmin, onSaved }: { sourceId: string; scope: { organizationId: string; projectId: string }; initial: CueCard[]; isAdmin: boolean; onSaved: () => Promise<unknown> }) {
  const [cards, setCards] = useState(initial);
  const save = useMutation({ mutationFn: () => putRawJson(`/api/v1/cues/sources/${encodeURIComponent(sourceId)}/cards`, { cards }, scope), onSuccess: () => void onSaved() });
  if (!isAdmin && !cards.length) return null;
  return <details className="cue-card-editor"><summary>Daily report cards <span>{cards.length}/14</span></summary><div className="cue-card-list">{cards.map((card, index) => <div className="cue-card-row" key={`${card.metricKey}-${index}`}><input aria-label={`Card ${index + 1} metric key`} value={card.metricKey} placeholder="custom.activity" disabled={!isAdmin} onChange={(event) => setCards((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, metricKey: event.target.value } : item))} /><input aria-label={`Card ${index + 1} daily label`} value={card.dailyLabel ?? ""} placeholder="Daily label" disabled={!isAdmin} onChange={(event) => setCards((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, dailyLabel: event.target.value || null } : item))} /><input aria-label={`Card ${index + 1} cumulative label`} value={card.cumulativeLabel ?? ""} placeholder="Cumulative label" disabled={!isAdmin} onChange={(event) => setCards((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, cumulativeLabel: event.target.value || null } : item))} /><label><input type="checkbox" checked={card.perActiveEnabled} disabled={!isAdmin} onChange={(event) => setCards((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, perActiveEnabled: event.target.checked } : item))} /> Per active user</label>{isAdmin ? <button className="mini-button destructive" onClick={() => setCards((current) => current.filter((_, itemIndex) => itemIndex !== index))}>Remove</button> : null}</div>)}</div>{isAdmin ? <div className="maintenance-actions"><button className="button" disabled={cards.length >= 14} onClick={() => setCards((current) => [...current, { metricKey: "", enabled: true, dailyLabel: null, cumulativeLabel: null, perActiveEnabled: false }])}>Add card</button><button className="button primary-button" disabled={save.isPending || cards.some((card) => !/^[a-z][a-z0-9_]*(?:\.[a-z][a-z0-9_]*){1,6}$/.test(card.metricKey))} onClick={() => save.mutate()}>{save.isPending ? "Saving…" : "Save card order"}</button></div> : null}{save.error ? <small role="alert">{save.error.message}</small> : null}</details>;
}
