// Generated from packages/sdk-contract/public-api.json. Do not edit by hand.
import Foundation

public enum NoxHereResource: String, CaseIterable, Sendable {
    case activity
    case feedback
    case incidents
    case planning
    case workspace
}

public enum NoxHereChangeSafety: String, Sendable {
    case safeRead = "safe_read"
    case idempotentWithEventKey = "idempotent_with_event_key"
    case conditionalWrite = "conditional_write"
    case writeNotSafeToRetry = "write_not_safe_to_retry"
    case destructive
}

public struct NoxHereOperation: Sendable, Equatable {
    public let id: String
    public let method: String
    public let path: String
    public let resource: NoxHereResource
    public let changeSafety: NoxHereChangeSafety
    public let servers: [String]
}

public enum NoxHereOperations {
    public static let operationCount = 149
    public static let all: [String: NoxHereOperation] = [
        "acknowledgeRepositories": .init(id: "acknowledgeRepositories", method: "POST", path: "/api/v1/repos/acknowledge", resource: .workspace, changeSafety: .writeNotSafeToRetry, servers: []),
        "archiveProject": .init(id: "archiveProject", method: "POST", path: "/api/v1/projects/{projectId}/archive", resource: .workspace, changeSafety: .destructive, servers: []),
        "archiveSpec": .init(id: "archiveSpec", method: "POST", path: "/api/v1/specs/{specId}/archive", resource: .planning, changeSafety: .destructive, servers: []),
        "assignIssue": .init(id: "assignIssue", method: "POST", path: "/api/v1/assign", resource: .planning, changeSafety: .writeNotSafeToRetry, servers: []),
        "assignSlackConnectionProject": .init(id: "assignSlackConnectionProject", method: "PATCH", path: "/api/v1/slack/connections/{connectionId}", resource: .workspace, changeSafety: .writeNotSafeToRetry, servers: []),
        "backfillProjectPullRequests": .init(id: "backfillProjectPullRequests", method: "POST", path: "/api/v1/projects/{projectId}/backfill-prs", resource: .workspace, changeSafety: .writeNotSafeToRetry, servers: []),
        "closeFeature": .init(id: "closeFeature", method: "DELETE", path: "/api/v1/features/{number}", resource: .planning, changeSafety: .destructive, servers: []),
        "closePullRequest": .init(id: "closePullRequest", method: "POST", path: "/api/v1/prs/close", resource: .activity, changeSafety: .destructive, servers: []),
        "createApiToken": .init(id: "createApiToken", method: "POST", path: "/api/v1/api-tokens", resource: .workspace, changeSafety: .writeNotSafeToRetry, servers: []),
        "createFeature": .init(id: "createFeature", method: "POST", path: "/api/v1/features", resource: .planning, changeSafety: .writeNotSafeToRetry, servers: []),
        "createGuestInvitation": .init(id: "createGuestInvitation", method: "POST", path: "/api/v1/guests/invites", resource: .workspace, changeSafety: .writeNotSafeToRetry, servers: []),
        "createNoxCueCustomFeature": .init(id: "createNoxCueCustomFeature", method: "POST", path: "/api/v1/cues/sources/{sourceId}/features", resource: .incidents, changeSafety: .writeNotSafeToRetry, servers: []),
        "createNoxCueCustomMetric": .init(id: "createNoxCueCustomMetric", method: "POST", path: "/api/v1/cues/sources/{sourceId}/custom-metrics", resource: .incidents, changeSafety: .writeNotSafeToRetry, servers: []),
        "createNoxCueKey": .init(id: "createNoxCueKey", method: "POST", path: "/api/v1/cues/sources/{sourceId}/keys", resource: .incidents, changeSafety: .writeNotSafeToRetry, servers: []),
        "createNoxCueSource": .init(id: "createNoxCueSource", method: "POST", path: "/api/v1/cues/sources", resource: .incidents, changeSafety: .writeNotSafeToRetry, servers: []),
        "createNoxSpotSite": .init(id: "createNoxSpotSite", method: "POST", path: "/api/v1/spots/sites", resource: .feedback, changeSafety: .writeNotSafeToRetry, servers: []),
        "createProject": .init(id: "createProject", method: "POST", path: "/api/v1/projects", resource: .workspace, changeSafety: .writeNotSafeToRetry, servers: []),
        "createSpec": .init(id: "createSpec", method: "POST", path: "/api/v1/specs", resource: .planning, changeSafety: .writeNotSafeToRetry, servers: []),
        "deleteFeatureAttachment": .init(id: "deleteFeatureAttachment", method: "DELETE", path: "/api/v1/features/{number}/attachments/{attachmentId}", resource: .planning, changeSafety: .destructive, servers: []),
        "deleteNoxCueCustomFeature": .init(id: "deleteNoxCueCustomFeature", method: "DELETE", path: "/api/v1/cues/sources/{sourceId}/features/{featureKey}", resource: .incidents, changeSafety: .destructive, servers: []),
        "deleteNoxCueCustomMetric": .init(id: "deleteNoxCueCustomMetric", method: "DELETE", path: "/api/v1/cues/sources/{sourceId}/custom-metrics/{metricKey}", resource: .incidents, changeSafety: .destructive, servers: []),
        "deleteNoxCueSource": .init(id: "deleteNoxCueSource", method: "DELETE", path: "/api/v1/cues/sources/{sourceId}", resource: .incidents, changeSafety: .destructive, servers: []),
        "deleteNoxSpotSite": .init(id: "deleteNoxSpotSite", method: "DELETE", path: "/api/v1/spots/sites/{siteId}", resource: .feedback, changeSafety: .destructive, servers: []),
        "deleteSpecAttachment": .init(id: "deleteSpecAttachment", method: "DELETE", path: "/api/v1/specs/{specId}/attachments/{attachmentId}", resource: .planning, changeSafety: .destructive, servers: []),
        "disconnectConnection": .init(id: "disconnectConnection", method: "POST", path: "/api/v1/integrations/connections/{provider}/disconnect", resource: .workspace, changeSafety: .destructive, servers: []),
        "disconnectSlackWorkspace": .init(id: "disconnectSlackWorkspace", method: "POST", path: "/api/v1/slack/disconnect", resource: .workspace, changeSafety: .destructive, servers: []),
        "downloadFeatureAttachment": .init(id: "downloadFeatureAttachment", method: "GET", path: "/api/v1/features/{number}/attachments/{attachmentId}", resource: .planning, changeSafety: .safeRead, servers: []),
        "downloadSpecAttachment": .init(id: "downloadSpecAttachment", method: "GET", path: "/api/v1/specs/{specId}/attachments/{attachmentId}", resource: .planning, changeSafety: .safeRead, servers: []),
        "exchangeLegacyNativeCredential": .init(id: "exchangeLegacyNativeCredential", method: "POST", path: "/api/v1/auth/native/exchange", resource: .workspace, changeSafety: .writeNotSafeToRetry, servers: []),
        "getActor": .init(id: "getActor", method: "GET", path: "/api/v1/actors/{actorId}", resource: .workspace, changeSafety: .safeRead, servers: []),
        "getAiSettings": .init(id: "getAiSettings", method: "GET", path: "/api/v1/llm-settings", resource: .activity, changeSafety: .safeRead, servers: []),
        "getBootstrapStatus": .init(id: "getBootstrapStatus", method: "GET", path: "/api/v1/bootstrap-status", resource: .workspace, changeSafety: .safeRead, servers: []),
        "getCueProjectActions": .init(id: "getCueProjectActions", method: "GET", path: "/api/v1/projects/{projectId}/cue/actions", resource: .incidents, changeSafety: .safeRead, servers: []),
        "getCueProjectAlertRules": .init(id: "getCueProjectAlertRules", method: "GET", path: "/api/v1/projects/{projectId}/cue/alert-rules", resource: .incidents, changeSafety: .safeRead, servers: []),
        "getCueProjectAlerts": .init(id: "getCueProjectAlerts", method: "GET", path: "/api/v1/projects/{projectId}/cue/alerts", resource: .incidents, changeSafety: .safeRead, servers: []),
        "getCueProjectDashboard": .init(id: "getCueProjectDashboard", method: "GET", path: "/api/v1/projects/{projectId}/cue/dashboard", resource: .incidents, changeSafety: .safeRead, servers: []),
        "getCueProjectStatEvents": .init(id: "getCueProjectStatEvents", method: "GET", path: "/api/v1/projects/{projectId}/cue/stat-events", resource: .incidents, changeSafety: .safeRead, servers: []),
        "getCurrentMember": .init(id: "getCurrentMember", method: "GET", path: "/api/v1/me", resource: .workspace, changeSafety: .safeRead, servers: []),
        "getCurrentWorkSummary": .init(id: "getCurrentWorkSummary", method: "GET", path: "/api/v1/feed/current-summary", resource: .activity, changeSafety: .safeRead, servers: []),
        "getEngineerActivity": .init(id: "getEngineerActivity", method: "GET", path: "/api/v1/engineer-activity", resource: .activity, changeSafety: .safeRead, servers: []),
        "getEngineerStats": .init(id: "getEngineerStats", method: "GET", path: "/api/v1/engineer-stats", resource: .activity, changeSafety: .safeRead, servers: []),
        "getFeedEvent": .init(id: "getFeedEvent", method: "GET", path: "/api/v1/events/{id}", resource: .activity, changeSafety: .safeRead, servers: []),
        "getGitHubComments": .init(id: "getGitHubComments", method: "GET", path: "/api/v1/github/comments", resource: .activity, changeSafety: .safeRead, servers: []),
        "getGitHubDetails": .init(id: "getGitHubDetails", method: "GET", path: "/api/v1/github/details", resource: .activity, changeSafety: .safeRead, servers: []),
        "getGitHubRateLimit": .init(id: "getGitHubRateLimit", method: "GET", path: "/api/v1/github/rate-limit", resource: .workspace, changeSafety: .safeRead, servers: []),
        "getIdentityProfile": .init(id: "getIdentityProfile", method: "GET", path: "/api/v1/auth/profile", resource: .workspace, changeSafety: .safeRead, servers: []),
        "getIntegrationStatus": .init(id: "getIntegrationStatus", method: "GET", path: "/api/v1/integrations/status", resource: .workspace, changeSafety: .safeRead, servers: []),
        "getIssue": .init(id: "getIssue", method: "GET", path: "/api/v1/issues/{repo}/{number}", resource: .activity, changeSafety: .safeRead, servers: []),
        "getNoxCueDailyHealth": .init(id: "getNoxCueDailyHealth", method: "GET", path: "/api/v1/cues/metrics", resource: .incidents, changeSafety: .safeRead, servers: []),
        "getNoxCueGitHubIssueSettings": .init(id: "getNoxCueGitHubIssueSettings", method: "GET", path: "/api/v1/cues/github-issues", resource: .incidents, changeSafety: .safeRead, servers: []),
        "getNoxCueProjectMetrics": .init(id: "getNoxCueProjectMetrics", method: "GET", path: "/api/v1/cues/projects/{projectId}/metrics", resource: .incidents, changeSafety: .safeRead, servers: []),
        "getNoxCueProjectOverview": .init(id: "getNoxCueProjectOverview", method: "GET", path: "/api/v1/cues/project-overview", resource: .incidents, changeSafety: .safeRead, servers: []),
        "getNoxFeed": .init(id: "getNoxFeed", method: "GET", path: "/api/v1/feed", resource: .activity, changeSafety: .safeRead, servers: []),
        "getNoxFeedDefaultPrompt": .init(id: "getNoxFeedDefaultPrompt", method: "GET", path: "/api/v1/noxfeed/release-notes-prompt", resource: .activity, changeSafety: .safeRead, servers: []),
        "getNoxService": .init(id: "getNoxService", method: "GET", path: "/api/v1/services/{service}", resource: .workspace, changeSafety: .safeRead, servers: []),
        "getNoxServiceConfig": .init(id: "getNoxServiceConfig", method: "GET", path: "/api/v1/services/{service}/config", resource: .workspace, changeSafety: .safeRead, servers: []),
        "getNoxServiceHealth": .init(id: "getNoxServiceHealth", method: "GET", path: "/api/v1/services/{service}/health", resource: .workspace, changeSafety: .safeRead, servers: []),
        "getNoxServiceSetup": .init(id: "getNoxServiceSetup", method: "GET", path: "/api/v1/services/{service}/setup", resource: .workspace, changeSafety: .safeRead, servers: []),
        "getNoxSpotProjectOverview": .init(id: "getNoxSpotProjectOverview", method: "GET", path: "/api/v1/spots/project-overview", resource: .feedback, changeSafety: .safeRead, servers: []),
        "getNoxSpotResolutionTemplate": .init(id: "getNoxSpotResolutionTemplate", method: "GET", path: "/api/v1/spots/sites/{siteId}/resolution-template", resource: .feedback, changeSafety: .safeRead, servers: []),
        "getOperatorUsage": .init(id: "getOperatorUsage", method: "GET", path: "/api/v1/operator/usage", resource: .workspace, changeSafety: .safeRead, servers: []),
        "getProjectActivity": .init(id: "getProjectActivity", method: "GET", path: "/api/v1/projects/{projectId}/activity", resource: .workspace, changeSafety: .safeRead, servers: []),
        "getProjectFeedback": .init(id: "getProjectFeedback", method: "GET", path: "/api/v1/projects/{projectId}/feedback", resource: .workspace, changeSafety: .safeRead, servers: []),
        "getProjectIncident": .init(id: "getProjectIncident", method: "GET", path: "/api/v1/projects/{projectId}/incidents/{incidentId}", resource: .workspace, changeSafety: .safeRead, servers: []),
        "getProjectIncidents": .init(id: "getProjectIncidents", method: "GET", path: "/api/v1/projects/{projectId}/incidents", resource: .workspace, changeSafety: .safeRead, servers: []),
        "getProjectIssues": .init(id: "getProjectIssues", method: "GET", path: "/api/v1/projects/{projectId}/issues", resource: .workspace, changeSafety: .safeRead, servers: []),
        "getProjectRouting": .init(id: "getProjectRouting", method: "GET", path: "/api/v1/projects/routing", resource: .workspace, changeSafety: .safeRead, servers: []),
        "getPublicNoxSpotConfig": .init(id: "getPublicNoxSpotConfig", method: "GET", path: "/api/spots/public/v1/sites/{siteId}/config", resource: .feedback, changeSafety: .safeRead, servers: ["https://api.noxspot.dev"]),
        "getPullRequest": .init(id: "getPullRequest", method: "GET", path: "/api/v1/prs/{repo}/{number}", resource: .activity, changeSafety: .safeRead, servers: []),
        "getSetupPlan": .init(id: "getSetupPlan", method: "GET", path: "/api/v1/integrations/setup", resource: .workspace, changeSafety: .safeRead, servers: []),
        "getSlackRouting": .init(id: "getSlackRouting", method: "GET", path: "/api/v1/integrations/slack/routing", resource: .workspace, changeSafety: .safeRead, servers: []),
        "getSlackStatus": .init(id: "getSlackStatus", method: "GET", path: "/api/v1/slack/status", resource: .workspace, changeSafety: .safeRead, servers: []),
        "getSpec": .init(id: "getSpec", method: "GET", path: "/api/v1/specs/{specId}", resource: .planning, changeSafety: .safeRead, servers: []),
        "getSyncStatus": .init(id: "getSyncStatus", method: "GET", path: "/api/v1/sync", resource: .workspace, changeSafety: .safeRead, servers: []),
        "getWorkspaceConfig": .init(id: "getWorkspaceConfig", method: "GET", path: "/api/v1/config/{key}", resource: .workspace, changeSafety: .safeRead, servers: []),
        "ingestNoxCueEvent": .init(id: "ingestNoxCueEvent", method: "POST", path: "/api/v1/cues/public/events", resource: .incidents, changeSafety: .idempotentWithEventKey, servers: []),
        "listActors": .init(id: "listActors", method: "GET", path: "/api/v1/actors", resource: .workspace, changeSafety: .safeRead, servers: []),
        "listApiTokens": .init(id: "listApiTokens", method: "GET", path: "/api/v1/api-tokens", resource: .workspace, changeSafety: .safeRead, servers: []),
        "listConnections": .init(id: "listConnections", method: "GET", path: "/api/v1/integrations/connections", resource: .workspace, changeSafety: .safeRead, servers: []),
        "listFeatureAttachments": .init(id: "listFeatureAttachments", method: "GET", path: "/api/v1/features/{number}/attachments", resource: .planning, changeSafety: .safeRead, servers: []),
        "listFeatures": .init(id: "listFeatures", method: "GET", path: "/api/v1/features", resource: .planning, changeSafety: .safeRead, servers: []),
        "listFeedEvents": .init(id: "listFeedEvents", method: "GET", path: "/api/v1/events", resource: .activity, changeSafety: .safeRead, servers: []),
        "listGitHubTeams": .init(id: "listGitHubTeams", method: "GET", path: "/api/v1/teams", resource: .workspace, changeSafety: .safeRead, servers: []),
        "listGuestAccess": .init(id: "listGuestAccess", method: "GET", path: "/api/v1/guests", resource: .workspace, changeSafety: .safeRead, servers: []),
        "listIssues": .init(id: "listIssues", method: "GET", path: "/api/v1/issues", resource: .activity, changeSafety: .safeRead, servers: []),
        "listMembers": .init(id: "listMembers", method: "GET", path: "/api/v1/members", resource: .workspace, changeSafety: .safeRead, servers: []),
        "listNoxCueCustomMetrics": .init(id: "listNoxCueCustomMetrics", method: "GET", path: "/api/v1/cues/sources/{sourceId}/custom-metrics", resource: .incidents, changeSafety: .safeRead, servers: []),
        "listNoxCueEvents": .init(id: "listNoxCueEvents", method: "GET", path: "/api/v1/cues/events", resource: .incidents, changeSafety: .safeRead, servers: []),
        "listNoxCueFeatures": .init(id: "listNoxCueFeatures", method: "GET", path: "/api/v1/cues/sources/{sourceId}/features", resource: .incidents, changeSafety: .safeRead, servers: []),
        "listNoxCueSources": .init(id: "listNoxCueSources", method: "GET", path: "/api/v1/cues/sources", resource: .incidents, changeSafety: .safeRead, servers: []),
        "listNoxServices": .init(id: "listNoxServices", method: "GET", path: "/api/v1/services", resource: .workspace, changeSafety: .safeRead, servers: []),
        "listNoxSpotSites": .init(id: "listNoxSpotSites", method: "GET", path: "/api/v1/spots/sites", resource: .feedback, changeSafety: .safeRead, servers: []),
        "listOperationFailures": .init(id: "listOperationFailures", method: "GET", path: "/api/v1/op-failures", resource: .workspace, changeSafety: .safeRead, servers: []),
        "listProjects": .init(id: "listProjects", method: "GET", path: "/api/v1/projects", resource: .workspace, changeSafety: .safeRead, servers: []),
        "listPullRequests": .init(id: "listPullRequests", method: "GET", path: "/api/v1/prs", resource: .activity, changeSafety: .safeRead, servers: []),
        "listRepositories": .init(id: "listRepositories", method: "GET", path: "/api/v1/repos", resource: .workspace, changeSafety: .safeRead, servers: []),
        "listSlackChannels": .init(id: "listSlackChannels", method: "GET", path: "/api/v1/slack/channels", resource: .workspace, changeSafety: .safeRead, servers: []),
        "listSpecAttachments": .init(id: "listSpecAttachments", method: "GET", path: "/api/v1/specs/{specId}/attachments", resource: .planning, changeSafety: .safeRead, servers: []),
        "listSpecs": .init(id: "listSpecs", method: "GET", path: "/api/v1/specs", resource: .planning, changeSafety: .safeRead, servers: []),
        "patchNoxServiceConfig": .init(id: "patchNoxServiceConfig", method: "PATCH", path: "/api/v1/services/{service}/config", resource: .workspace, changeSafety: .conditionalWrite, servers: []),
        "patchSlackRouting": .init(id: "patchSlackRouting", method: "PATCH", path: "/api/v1/integrations/slack/routing", resource: .workspace, changeSafety: .writeNotSafeToRetry, servers: []),
        "pollNativeDeviceAuthorization": .init(id: "pollNativeDeviceAuthorization", method: "POST", path: "/api/v1/auth/native/device/poll", resource: .workspace, changeSafety: .writeNotSafeToRetry, servers: []),
        "previewNoxSpotResolutionTemplate": .init(id: "previewNoxSpotResolutionTemplate", method: "POST", path: "/api/v1/spots/sites/{siteId}/resolution-template/preview", resource: .feedback, changeSafety: .writeNotSafeToRetry, servers: []),
        "putAiSettings": .init(id: "putAiSettings", method: "PUT", path: "/api/v1/llm-settings", resource: .activity, changeSafety: .writeNotSafeToRetry, servers: []),
        "putNoxCueGitHubIssueSettings": .init(id: "putNoxCueGitHubIssueSettings", method: "PUT", path: "/api/v1/cues/github-issues", resource: .incidents, changeSafety: .writeNotSafeToRetry, servers: []),
        "putWorkspaceConfig": .init(id: "putWorkspaceConfig", method: "PUT", path: "/api/v1/config/{key}", resource: .workspace, changeSafety: .writeNotSafeToRetry, servers: []),
        "recordAppActivity": .init(id: "recordAppActivity", method: "POST", path: "/api/v1/app-activity", resource: .workspace, changeSafety: .writeNotSafeToRetry, servers: []),
        "recoverRepositoryHistory": .init(id: "recoverRepositoryHistory", method: "POST", path: "/api/v1/recover-repo-history", resource: .workspace, changeSafety: .writeNotSafeToRetry, servers: []),
        "refreshNativeSession": .init(id: "refreshNativeSession", method: "POST", path: "/api/v1/auth/native/refresh", resource: .workspace, changeSafety: .writeNotSafeToRetry, servers: []),
        "reopenResolvedNoxSpotReport": .init(id: "reopenResolvedNoxSpotReport", method: "POST", path: "/api/spots/public/v1/resolution-responses/{token}", resource: .feedback, changeSafety: .writeNotSafeToRetry, servers: ["https://api.noxspot.dev"]),
        "restoreProject": .init(id: "restoreProject", method: "DELETE", path: "/api/v1/projects/{projectId}/archive", resource: .workspace, changeSafety: .destructive, servers: []),
        "restoreSpec": .init(id: "restoreSpec", method: "DELETE", path: "/api/v1/specs/{specId}/archive", resource: .planning, changeSafety: .destructive, servers: []),
        "retrieveProject": .init(id: "retrieveProject", method: "GET", path: "/api/v1/projects/{projectId}/retrieval", resource: .workspace, changeSafety: .safeRead, servers: []),
        "retryNoxSpotDeliveries": .init(id: "retryNoxSpotDeliveries", method: "POST", path: "/api/v1/spots/sites/{siteId}/retry-deliveries", resource: .feedback, changeSafety: .writeNotSafeToRetry, servers: []),
        "revokeApiToken": .init(id: "revokeApiToken", method: "DELETE", path: "/api/v1/api-tokens/{id}", resource: .workspace, changeSafety: .destructive, servers: []),
        "revokeBrowserSession": .init(id: "revokeBrowserSession", method: "POST", path: "/api/v1/auth/logout", resource: .workspace, changeSafety: .destructive, servers: []),
        "revokeGuestGrant": .init(id: "revokeGuestGrant", method: "DELETE", path: "/api/v1/guests/grants/{grantId}", resource: .workspace, changeSafety: .destructive, servers: []),
        "revokeGuestInvitation": .init(id: "revokeGuestInvitation", method: "DELETE", path: "/api/v1/guests/invites/{inviteId}", resource: .workspace, changeSafety: .destructive, servers: []),
        "revokeNativeSession": .init(id: "revokeNativeSession", method: "POST", path: "/api/v1/auth/native/revoke", resource: .workspace, changeSafety: .destructive, servers: []),
        "revokeNoxCueKey": .init(id: "revokeNoxCueKey", method: "DELETE", path: "/api/v1/cues/sources/{sourceId}/keys/{keyId}", resource: .incidents, changeSafety: .destructive, servers: []),
        "rotateApiToken": .init(id: "rotateApiToken", method: "POST", path: "/api/v1/api-tokens/{id}/rotate", resource: .workspace, changeSafety: .writeNotSafeToRetry, servers: []),
        "searchWorkspace": .init(id: "searchWorkspace", method: "GET", path: "/api/v1/search", resource: .activity, changeSafety: .safeRead, servers: []),
        "setIssueState": .init(id: "setIssueState", method: "POST", path: "/api/v1/issue-state", resource: .planning, changeSafety: .writeNotSafeToRetry, servers: []),
        "startConnection": .init(id: "startConnection", method: "POST", path: "/api/v1/integrations/connections/{provider}/start", resource: .workspace, changeSafety: .writeNotSafeToRetry, servers: []),
        "startNativeDeviceAuthorization": .init(id: "startNativeDeviceAuthorization", method: "POST", path: "/api/v1/auth/native/device/start", resource: .workspace, changeSafety: .writeNotSafeToRetry, servers: []),
        "submitPublicNoxSpotErrors": .init(id: "submitPublicNoxSpotErrors", method: "POST", path: "/api/spots/public/v1/errors", resource: .feedback, changeSafety: .writeNotSafeToRetry, servers: ["https://api.noxspot.dev"]),
        "submitPublicNoxSpotReport": .init(id: "submitPublicNoxSpotReport", method: "POST", path: "/api/spots/public/v1/reports", resource: .feedback, changeSafety: .writeNotSafeToRetry, servers: ["https://api.noxspot.dev"]),
        "syncGitHubData": .init(id: "syncGitHubData", method: "POST", path: "/api/v1/sync", resource: .workspace, changeSafety: .writeNotSafeToRetry, servers: []),
        "syncGitHubEvents": .init(id: "syncGitHubEvents", method: "POST", path: "/api/v1/sync-events", resource: .workspace, changeSafety: .writeNotSafeToRetry, servers: []),
        "testNoxCueSource": .init(id: "testNoxCueSource", method: "POST", path: "/api/v1/cues/sources/{sourceId}/health/test", resource: .incidents, changeSafety: .writeNotSafeToRetry, servers: []),
        "testNoxSpotResolutionTemplate": .init(id: "testNoxSpotResolutionTemplate", method: "POST", path: "/api/v1/spots/sites/{siteId}/resolution-template/test", resource: .feedback, changeSafety: .writeNotSafeToRetry, servers: []),
        "testSlackDestination": .init(id: "testSlackDestination", method: "POST", path: "/api/v1/slack/test", resource: .workspace, changeSafety: .writeNotSafeToRetry, servers: []),
        "testSlackRoute": .init(id: "testSlackRoute", method: "POST", path: "/api/v1/integrations/slack/test", resource: .workspace, changeSafety: .writeNotSafeToRetry, servers: []),
        "updateActor": .init(id: "updateActor", method: "PATCH", path: "/api/v1/actors/{actorId}", resource: .workspace, changeSafety: .writeNotSafeToRetry, servers: []),
        "updateCueProjectActions": .init(id: "updateCueProjectActions", method: "PUT", path: "/api/v1/projects/{projectId}/cue/actions", resource: .incidents, changeSafety: .writeNotSafeToRetry, servers: []),
        "updateFeature": .init(id: "updateFeature", method: "PATCH", path: "/api/v1/features/{number}", resource: .planning, changeSafety: .writeNotSafeToRetry, servers: []),
        "updateNoxCueCustomFeature": .init(id: "updateNoxCueCustomFeature", method: "PUT", path: "/api/v1/cues/sources/{sourceId}/features/{featureKey}", resource: .incidents, changeSafety: .writeNotSafeToRetry, servers: []),
        "updateNoxCueCustomMetric": .init(id: "updateNoxCueCustomMetric", method: "PUT", path: "/api/v1/cues/sources/{sourceId}/custom-metrics/{metricKey}", resource: .incidents, changeSafety: .writeNotSafeToRetry, servers: []),
        "updateNoxCueErrorStatus": .init(id: "updateNoxCueErrorStatus", method: "PUT", path: "/api/v1/cues/errors/{sourceId}/{fingerprint}", resource: .incidents, changeSafety: .writeNotSafeToRetry, servers: []),
        "updateNoxCueProjectMetrics": .init(id: "updateNoxCueProjectMetrics", method: "PUT", path: "/api/v1/cues/projects/{projectId}/metrics", resource: .incidents, changeSafety: .writeNotSafeToRetry, servers: []),
        "updateNoxCueSource": .init(id: "updateNoxCueSource", method: "PUT", path: "/api/v1/cues/sources/{sourceId}", resource: .incidents, changeSafety: .writeNotSafeToRetry, servers: []),
        "updateNoxSpotReport": .init(id: "updateNoxSpotReport", method: "PATCH", path: "/api/v1/spots/reports/{reportId}", resource: .feedback, changeSafety: .writeNotSafeToRetry, servers: []),
        "updateNoxSpotResolutionTemplate": .init(id: "updateNoxSpotResolutionTemplate", method: "PATCH", path: "/api/v1/spots/sites/{siteId}/resolution-template", resource: .feedback, changeSafety: .conditionalWrite, servers: []),
        "updateNoxSpotSite": .init(id: "updateNoxSpotSite", method: "PATCH", path: "/api/v1/spots/sites/{siteId}", resource: .feedback, changeSafety: .writeNotSafeToRetry, servers: []),
        "updateProjectIncident": .init(id: "updateProjectIncident", method: "PATCH", path: "/api/v1/projects/{projectId}/incidents/{incidentId}", resource: .workspace, changeSafety: .writeNotSafeToRetry, servers: []),
        "updateProjectRouting": .init(id: "updateProjectRouting", method: "PUT", path: "/api/v1/projects/{projectId}/routing", resource: .workspace, changeSafety: .writeNotSafeToRetry, servers: []),
        "updateSpec": .init(id: "updateSpec", method: "PATCH", path: "/api/v1/specs/{specId}", resource: .planning, changeSafety: .writeNotSafeToRetry, servers: []),
        "uploadFeatureAttachment": .init(id: "uploadFeatureAttachment", method: "POST", path: "/api/v1/features/{number}/attachments", resource: .planning, changeSafety: .writeNotSafeToRetry, servers: []),
        "uploadSpecAttachment": .init(id: "uploadSpecAttachment", method: "POST", path: "/api/v1/specs/{specId}/attachments", resource: .planning, changeSafety: .writeNotSafeToRetry, servers: []),
    ]
}
