# Generated public typing surface. Runtime implementation lives in client.py.
from __future__ import annotations

from typing import Any, Callable, Mapping, Protocol, Sequence
from . import models
from .models import JsonValue

TransportResult = tuple[int, Mapping[str, str], bytes]
class Transport(Protocol):
    def __call__(self, method: str, url: str, headers: Mapping[str, str], body: bytes | None) -> TransportResult: ...

class NoxHereApiError(RuntimeError):
    status: int
    operation_id: str
    details: Any
    code: str
    request_id: str | None
    retry_after: float | None
    retryable: bool
class NoxHereTransportError(RuntimeError):
    operation_id: str
    retryable: bool

class ResourceClient:
    def operation_ids(self) -> tuple[str, ...]: ...
class AsyncResourceClient:
    def operation_ids(self) -> tuple[str, ...]: ...

class WorkspaceClient(ResourceClient):
    def acknowledge_repositories(self, *, body: models.AcknowledgeRepositoriesBody, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def archive_project(self, *, path: models.ArchiveProjectPath, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def assign_slack_connection_project(self, *, path: models.AssignSlackConnectionProjectPath, body: models.SlackProjectAssignment, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def backfill_project_pull_requests(self, *, path: models.BackfillProjectPullRequestsPath, body: models.JsonValue | None = None, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def create_api_token(self, *, body: models.ApiTokenCreate, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def create_guest_invitation(self, *, body: models.JsonValue | None = None, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def create_planning_task(self, *, body: models.PlanningTaskCreate, headers: Mapping[str, str] | None = None) -> models.PlanningTask: ...
    def create_project(self, *, body: models.JsonValue, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def delete_planning_task(self, *, path: models.DeletePlanningTaskPath, headers: Mapping[str, str] | None = None) -> models.MutationReceipt: ...
    def disconnect_connection(self, *, path: models.DisconnectConnectionPath, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def disconnect_slack_workspace(self, *, body: models.JsonValue | None = None, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def draft_planning_item(self, *, body: models.PlanningAssistRequest, headers: Mapping[str, str] | None = None) -> models.PlanningAssistResponse: ...
    def exchange_legacy_native_credential(self, *, body: models.ExchangeLegacyNativeCredentialBody, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def get_actor(self, *, path: models.GetActorPath, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def get_bootstrap_status(self, *, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def get_current_member(self, *, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def get_git_hub_rate_limit(self, *, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def get_identity_profile(self, *, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def get_integration_status(self, *, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def get_nox_service(self, *, path: models.GetNoxServicePath, headers: Mapping[str, str] | None = None) -> models.ServiceDetail: ...
    def get_nox_service_config(self, *, path: models.GetNoxServiceConfigPath, headers: Mapping[str, str] | None = None) -> models.ServiceConfig: ...
    def get_nox_service_health(self, *, path: models.GetNoxServiceHealthPath, headers: Mapping[str, str] | None = None) -> models.ServiceHealth: ...
    def get_nox_service_setup(self, *, path: models.GetNoxServiceSetupPath, headers: Mapping[str, str] | None = None) -> models.ServiceSetupDetail: ...
    def get_operator_usage(self, *, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def get_project_activity(self, *, path: models.GetProjectActivityPath, headers: Mapping[str, str] | None = None) -> models.ApiRecord: ...
    def get_project_feedback(self, *, path: models.GetProjectFeedbackPath, headers: Mapping[str, str] | None = None) -> models.ApiRecord: ...
    def get_project_incident(self, *, path: models.GetProjectIncidentPath, headers: Mapping[str, str] | None = None) -> models.ApiRecord: ...
    def get_project_incidents(self, *, path: models.GetProjectIncidentsPath, headers: Mapping[str, str] | None = None) -> models.ApiRecord: ...
    def get_project_issues(self, *, path: models.GetProjectIssuesPath, headers: Mapping[str, str] | None = None) -> models.ApiRecord: ...
    def get_project_routing(self, *, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def get_setup_plan(self, *, headers: Mapping[str, str] | None = None) -> models.SetupPlan: ...
    def get_slack_routing(self, *, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def get_slack_status(self, *, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def get_sync_status(self, *, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def get_workspace_config(self, *, path: models.GetWorkspaceConfigPath, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def list_actors(self, *, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def list_api_tokens(self, *, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def list_connections(self, *, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def list_git_hub_teams(self, *, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def list_guest_access(self, *, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def list_members(self, *, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def list_nox_services(self, *, headers: Mapping[str, str] | None = None) -> models.ServiceCatalog: ...
    def list_operation_failures(self, *, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def list_planning_tasks(self, *, query: models.ListPlanningTasksQuery | None = None, headers: Mapping[str, str] | None = None) -> list[models.PlanningTask]: ...
    def list_projects(self, *, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def list_repositories(self, *, query: models.ListRepositoriesQuery | None = None, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def list_slack_channels(self, *, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def patch_nox_service_config(self, *, path: models.PatchNoxServiceConfigPath, body: models.ServiceConfigPatch, headers: Mapping[str, str] | None = None) -> models.ServiceConfig: ...
    def patch_slack_routing(self, *, body: models.RoutingPatch, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def poll_native_device_authorization(self, *, body: models.PollNativeDeviceAuthorizationBody, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def put_workspace_config(self, *, path: models.PutWorkspaceConfigPath, body: models.JsonValue | None = None, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def record_app_activity(self, *, body: models.JsonValue | None = None, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def recover_repository_history(self, *, body: models.JsonValue | None = None, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def refresh_native_session(self, *, body: models.RefreshNativeSessionBody, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def restore_project(self, *, path: models.RestoreProjectPath, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def retrieve_project(self, *, path: models.RetrieveProjectPath, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def revoke_api_token(self, *, path: models.RevokeApiTokenPath, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def revoke_browser_session(self, *, body: models.JsonValue | None = None, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def revoke_guest_grant(self, *, path: models.RevokeGuestGrantPath, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def revoke_guest_invitation(self, *, path: models.RevokeGuestInvitationPath, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def revoke_native_session(self, *, body: models.RevokeNativeSessionBody, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def rotate_api_token(self, *, path: models.RotateApiTokenPath, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def send_slack_message(self, *, body: models.SlackMessageRequest, headers: Mapping[str, str] | None = None) -> models.SlackMessageDelivery: ...
    def start_connection(self, *, path: models.StartConnectionPath, body: models.StartConnectionBody | None = None, headers: Mapping[str, str] | None = None) -> models.UserAction: ...
    def start_native_device_authorization(self, *, body: models.StartNativeDeviceAuthorizationBody, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def submit_developer_feedback(self, *, body: models.DeveloperFeedbackCreate, headers: Mapping[str, str] | None = None) -> models.DeveloperFeedbackReceipt: ...
    def sync_git_hub_data(self, *, body: models.JsonValue | None = None, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def sync_git_hub_events(self, *, body: models.JsonValue | None = None, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def test_slack_destination(self, *, body: models.JsonValue | None = None, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def test_slack_route(self, *, body: models.RouteTest, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def update_actor(self, *, path: models.UpdateActorPath, body: models.ActorPatch, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def update_planning_task(self, *, path: models.UpdatePlanningTaskPath, body: models.PlanningTaskPatch, headers: Mapping[str, str] | None = None) -> models.PlanningTask: ...
    def update_project_incident(self, *, path: models.UpdateProjectIncidentPath, body: models.ApiRecord, headers: Mapping[str, str] | None = None) -> models.ApiRecord: ...
    def update_project_routing(self, *, path: models.UpdateProjectRoutingPath, body: models.ProjectRoutingInput, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...

class AsyncWorkspaceClient(AsyncResourceClient):
    async def acknowledge_repositories(self, *, body: models.AcknowledgeRepositoriesBody, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def archive_project(self, *, path: models.ArchiveProjectPath, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def assign_slack_connection_project(self, *, path: models.AssignSlackConnectionProjectPath, body: models.SlackProjectAssignment, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def backfill_project_pull_requests(self, *, path: models.BackfillProjectPullRequestsPath, body: models.JsonValue | None = None, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def create_api_token(self, *, body: models.ApiTokenCreate, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def create_guest_invitation(self, *, body: models.JsonValue | None = None, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def create_planning_task(self, *, body: models.PlanningTaskCreate, headers: Mapping[str, str] | None = None) -> models.PlanningTask: ...
    async def create_project(self, *, body: models.JsonValue, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def delete_planning_task(self, *, path: models.DeletePlanningTaskPath, headers: Mapping[str, str] | None = None) -> models.MutationReceipt: ...
    async def disconnect_connection(self, *, path: models.DisconnectConnectionPath, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def disconnect_slack_workspace(self, *, body: models.JsonValue | None = None, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def draft_planning_item(self, *, body: models.PlanningAssistRequest, headers: Mapping[str, str] | None = None) -> models.PlanningAssistResponse: ...
    async def exchange_legacy_native_credential(self, *, body: models.ExchangeLegacyNativeCredentialBody, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def get_actor(self, *, path: models.GetActorPath, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def get_bootstrap_status(self, *, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def get_current_member(self, *, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def get_git_hub_rate_limit(self, *, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def get_identity_profile(self, *, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def get_integration_status(self, *, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def get_nox_service(self, *, path: models.GetNoxServicePath, headers: Mapping[str, str] | None = None) -> models.ServiceDetail: ...
    async def get_nox_service_config(self, *, path: models.GetNoxServiceConfigPath, headers: Mapping[str, str] | None = None) -> models.ServiceConfig: ...
    async def get_nox_service_health(self, *, path: models.GetNoxServiceHealthPath, headers: Mapping[str, str] | None = None) -> models.ServiceHealth: ...
    async def get_nox_service_setup(self, *, path: models.GetNoxServiceSetupPath, headers: Mapping[str, str] | None = None) -> models.ServiceSetupDetail: ...
    async def get_operator_usage(self, *, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def get_project_activity(self, *, path: models.GetProjectActivityPath, headers: Mapping[str, str] | None = None) -> models.ApiRecord: ...
    async def get_project_feedback(self, *, path: models.GetProjectFeedbackPath, headers: Mapping[str, str] | None = None) -> models.ApiRecord: ...
    async def get_project_incident(self, *, path: models.GetProjectIncidentPath, headers: Mapping[str, str] | None = None) -> models.ApiRecord: ...
    async def get_project_incidents(self, *, path: models.GetProjectIncidentsPath, headers: Mapping[str, str] | None = None) -> models.ApiRecord: ...
    async def get_project_issues(self, *, path: models.GetProjectIssuesPath, headers: Mapping[str, str] | None = None) -> models.ApiRecord: ...
    async def get_project_routing(self, *, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def get_setup_plan(self, *, headers: Mapping[str, str] | None = None) -> models.SetupPlan: ...
    async def get_slack_routing(self, *, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def get_slack_status(self, *, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def get_sync_status(self, *, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def get_workspace_config(self, *, path: models.GetWorkspaceConfigPath, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def list_actors(self, *, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def list_api_tokens(self, *, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def list_connections(self, *, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def list_git_hub_teams(self, *, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def list_guest_access(self, *, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def list_members(self, *, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def list_nox_services(self, *, headers: Mapping[str, str] | None = None) -> models.ServiceCatalog: ...
    async def list_operation_failures(self, *, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def list_planning_tasks(self, *, query: models.ListPlanningTasksQuery | None = None, headers: Mapping[str, str] | None = None) -> list[models.PlanningTask]: ...
    async def list_projects(self, *, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def list_repositories(self, *, query: models.ListRepositoriesQuery | None = None, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def list_slack_channels(self, *, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def patch_nox_service_config(self, *, path: models.PatchNoxServiceConfigPath, body: models.ServiceConfigPatch, headers: Mapping[str, str] | None = None) -> models.ServiceConfig: ...
    async def patch_slack_routing(self, *, body: models.RoutingPatch, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def poll_native_device_authorization(self, *, body: models.PollNativeDeviceAuthorizationBody, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def put_workspace_config(self, *, path: models.PutWorkspaceConfigPath, body: models.JsonValue | None = None, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def record_app_activity(self, *, body: models.JsonValue | None = None, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def recover_repository_history(self, *, body: models.JsonValue | None = None, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def refresh_native_session(self, *, body: models.RefreshNativeSessionBody, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def restore_project(self, *, path: models.RestoreProjectPath, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def retrieve_project(self, *, path: models.RetrieveProjectPath, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def revoke_api_token(self, *, path: models.RevokeApiTokenPath, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def revoke_browser_session(self, *, body: models.JsonValue | None = None, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def revoke_guest_grant(self, *, path: models.RevokeGuestGrantPath, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def revoke_guest_invitation(self, *, path: models.RevokeGuestInvitationPath, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def revoke_native_session(self, *, body: models.RevokeNativeSessionBody, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def rotate_api_token(self, *, path: models.RotateApiTokenPath, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def send_slack_message(self, *, body: models.SlackMessageRequest, headers: Mapping[str, str] | None = None) -> models.SlackMessageDelivery: ...
    async def start_connection(self, *, path: models.StartConnectionPath, body: models.StartConnectionBody | None = None, headers: Mapping[str, str] | None = None) -> models.UserAction: ...
    async def start_native_device_authorization(self, *, body: models.StartNativeDeviceAuthorizationBody, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def submit_developer_feedback(self, *, body: models.DeveloperFeedbackCreate, headers: Mapping[str, str] | None = None) -> models.DeveloperFeedbackReceipt: ...
    async def sync_git_hub_data(self, *, body: models.JsonValue | None = None, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def sync_git_hub_events(self, *, body: models.JsonValue | None = None, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def test_slack_destination(self, *, body: models.JsonValue | None = None, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def test_slack_route(self, *, body: models.RouteTest, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def update_actor(self, *, path: models.UpdateActorPath, body: models.ActorPatch, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def update_planning_task(self, *, path: models.UpdatePlanningTaskPath, body: models.PlanningTaskPatch, headers: Mapping[str, str] | None = None) -> models.PlanningTask: ...
    async def update_project_incident(self, *, path: models.UpdateProjectIncidentPath, body: models.ApiRecord, headers: Mapping[str, str] | None = None) -> models.ApiRecord: ...
    async def update_project_routing(self, *, path: models.UpdateProjectRoutingPath, body: models.ProjectRoutingInput, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...

class ActivityClient(ResourceClient):
    def close_pull_request(self, *, body: models.ClosePullRequestBody, headers: Mapping[str, str] | None = None) -> models.MutationReceipt: ...
    def get_ai_settings(self, *, headers: Mapping[str, str] | None = None) -> models.ApiRecord: ...
    def get_current_work_summary(self, *, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def get_engineer_activity(self, *, query: models.GetEngineerActivityQuery, headers: Mapping[str, str] | None = None) -> models.ApiRecord: ...
    def get_engineer_stats(self, *, headers: Mapping[str, str] | None = None) -> models.ApiRecord: ...
    def get_feed_event(self, *, path: models.GetFeedEventPath, headers: Mapping[str, str] | None = None) -> models.ApiRecord: ...
    def get_git_hub_comments(self, *, headers: Mapping[str, str] | None = None) -> models.ApiRecord: ...
    def get_git_hub_details(self, *, headers: Mapping[str, str] | None = None) -> models.ApiRecord: ...
    def get_issue(self, *, path: models.GetIssuePath, headers: Mapping[str, str] | None = None) -> models.ApiRecord: ...
    def get_nox_feed(self, *, query: models.GetNoxFeedQuery | None = None, headers: Mapping[str, str] | None = None) -> models.FeedPage: ...
    def get_nox_feed_default_prompt(self, *, headers: Mapping[str, str] | None = None) -> models.ApiRecord: ...
    def get_pull_request(self, *, path: models.GetPullRequestPath, headers: Mapping[str, str] | None = None) -> models.ApiRecord: ...
    def list_feed_events(self, *, headers: Mapping[str, str] | None = None) -> models.ApiRecord: ...
    def list_issues(self, *, query: models.ListIssuesQuery | None = None, headers: Mapping[str, str] | None = None) -> models.RecordCollection: ...
    def list_pull_requests(self, *, query: models.ListPullRequestsQuery | None = None, headers: Mapping[str, str] | None = None) -> models.RecordCollection: ...
    def put_ai_settings(self, *, body: models.PutAiSettingsBody, headers: Mapping[str, str] | None = None) -> models.MutationReceipt: ...
    def search_workspace(self, *, query: models.SearchWorkspaceQuery | None = None, headers: Mapping[str, str] | None = None) -> models.ApiRecord: ...

class AsyncActivityClient(AsyncResourceClient):
    async def close_pull_request(self, *, body: models.ClosePullRequestBody, headers: Mapping[str, str] | None = None) -> models.MutationReceipt: ...
    async def get_ai_settings(self, *, headers: Mapping[str, str] | None = None) -> models.ApiRecord: ...
    async def get_current_work_summary(self, *, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def get_engineer_activity(self, *, query: models.GetEngineerActivityQuery, headers: Mapping[str, str] | None = None) -> models.ApiRecord: ...
    async def get_engineer_stats(self, *, headers: Mapping[str, str] | None = None) -> models.ApiRecord: ...
    async def get_feed_event(self, *, path: models.GetFeedEventPath, headers: Mapping[str, str] | None = None) -> models.ApiRecord: ...
    async def get_git_hub_comments(self, *, headers: Mapping[str, str] | None = None) -> models.ApiRecord: ...
    async def get_git_hub_details(self, *, headers: Mapping[str, str] | None = None) -> models.ApiRecord: ...
    async def get_issue(self, *, path: models.GetIssuePath, headers: Mapping[str, str] | None = None) -> models.ApiRecord: ...
    async def get_nox_feed(self, *, query: models.GetNoxFeedQuery | None = None, headers: Mapping[str, str] | None = None) -> models.FeedPage: ...
    async def get_nox_feed_default_prompt(self, *, headers: Mapping[str, str] | None = None) -> models.ApiRecord: ...
    async def get_pull_request(self, *, path: models.GetPullRequestPath, headers: Mapping[str, str] | None = None) -> models.ApiRecord: ...
    async def list_feed_events(self, *, headers: Mapping[str, str] | None = None) -> models.ApiRecord: ...
    async def list_issues(self, *, query: models.ListIssuesQuery | None = None, headers: Mapping[str, str] | None = None) -> models.RecordCollection: ...
    async def list_pull_requests(self, *, query: models.ListPullRequestsQuery | None = None, headers: Mapping[str, str] | None = None) -> models.RecordCollection: ...
    async def put_ai_settings(self, *, body: models.PutAiSettingsBody, headers: Mapping[str, str] | None = None) -> models.MutationReceipt: ...
    async def search_workspace(self, *, query: models.SearchWorkspaceQuery | None = None, headers: Mapping[str, str] | None = None) -> models.ApiRecord: ...

class PlanningClient(ResourceClient):
    def archive_spec(self, *, path: models.ArchiveSpecPath, headers: Mapping[str, str] | None = None) -> models.MutationReceipt: ...
    def assign_issue(self, *, body: models.JsonValue | None = None, headers: Mapping[str, str] | None = None) -> models.ApiRecord: ...
    def close_feature(self, *, path: models.CloseFeaturePath, headers: Mapping[str, str] | None = None) -> models.MutationReceipt: ...
    def create_feature(self, *, body: models.FeatureCreate, headers: Mapping[str, str] | None = None) -> models.Feature: ...
    def create_spec(self, *, body: models.SpecInput, headers: Mapping[str, str] | None = None) -> models.Spec: ...
    def delete_feature_attachment(self, *, path: models.DeleteFeatureAttachmentPath, headers: Mapping[str, str] | None = None) -> models.MutationReceipt: ...
    def delete_spec_attachment(self, *, path: models.DeleteSpecAttachmentPath, headers: Mapping[str, str] | None = None) -> models.MutationReceipt: ...
    def download_feature_attachment(self, *, path: models.DownloadFeatureAttachmentPath, headers: Mapping[str, str] | None = None) -> bytes: ...
    def download_spec_attachment(self, *, path: models.DownloadSpecAttachmentPath, headers: Mapping[str, str] | None = None) -> bytes: ...
    def get_spec(self, *, path: models.GetSpecPath, headers: Mapping[str, str] | None = None) -> models.Spec: ...
    def list_feature_attachments(self, *, path: models.ListFeatureAttachmentsPath, headers: Mapping[str, str] | None = None) -> models.SpecAttachmentList: ...
    def list_features(self, *, query: models.ListFeaturesQuery | None = None, headers: Mapping[str, str] | None = None) -> models.FeatureList: ...
    def list_spec_attachments(self, *, path: models.ListSpecAttachmentsPath, headers: Mapping[str, str] | None = None) -> models.SpecAttachmentList: ...
    def list_specs(self, *, query: models.ListSpecsQuery | None = None, headers: Mapping[str, str] | None = None) -> models.SpecList: ...
    def restore_spec(self, *, path: models.RestoreSpecPath, headers: Mapping[str, str] | None = None) -> models.MutationReceipt: ...
    def set_issue_state(self, *, body: models.JsonValue | None = None, headers: Mapping[str, str] | None = None) -> models.MutationReceipt: ...
    def update_feature(self, *, path: models.UpdateFeaturePath, body: models.FeaturePatch, headers: Mapping[str, str] | None = None) -> models.Feature: ...
    def update_spec(self, *, path: models.UpdateSpecPath, body: models.SpecPatch, headers: Mapping[str, str] | None = None) -> models.Spec: ...
    def upload_feature_attachment(self, *, path: models.UploadFeatureAttachmentPath, body: Mapping[str, Any], headers: Mapping[str, str] | None = None) -> models.SpecAttachment: ...
    def upload_spec_attachment(self, *, path: models.UploadSpecAttachmentPath, body: Mapping[str, Any], headers: Mapping[str, str] | None = None) -> models.SpecAttachment: ...

class AsyncPlanningClient(AsyncResourceClient):
    async def archive_spec(self, *, path: models.ArchiveSpecPath, headers: Mapping[str, str] | None = None) -> models.MutationReceipt: ...
    async def assign_issue(self, *, body: models.JsonValue | None = None, headers: Mapping[str, str] | None = None) -> models.ApiRecord: ...
    async def close_feature(self, *, path: models.CloseFeaturePath, headers: Mapping[str, str] | None = None) -> models.MutationReceipt: ...
    async def create_feature(self, *, body: models.FeatureCreate, headers: Mapping[str, str] | None = None) -> models.Feature: ...
    async def create_spec(self, *, body: models.SpecInput, headers: Mapping[str, str] | None = None) -> models.Spec: ...
    async def delete_feature_attachment(self, *, path: models.DeleteFeatureAttachmentPath, headers: Mapping[str, str] | None = None) -> models.MutationReceipt: ...
    async def delete_spec_attachment(self, *, path: models.DeleteSpecAttachmentPath, headers: Mapping[str, str] | None = None) -> models.MutationReceipt: ...
    async def download_feature_attachment(self, *, path: models.DownloadFeatureAttachmentPath, headers: Mapping[str, str] | None = None) -> bytes: ...
    async def download_spec_attachment(self, *, path: models.DownloadSpecAttachmentPath, headers: Mapping[str, str] | None = None) -> bytes: ...
    async def get_spec(self, *, path: models.GetSpecPath, headers: Mapping[str, str] | None = None) -> models.Spec: ...
    async def list_feature_attachments(self, *, path: models.ListFeatureAttachmentsPath, headers: Mapping[str, str] | None = None) -> models.SpecAttachmentList: ...
    async def list_features(self, *, query: models.ListFeaturesQuery | None = None, headers: Mapping[str, str] | None = None) -> models.FeatureList: ...
    async def list_spec_attachments(self, *, path: models.ListSpecAttachmentsPath, headers: Mapping[str, str] | None = None) -> models.SpecAttachmentList: ...
    async def list_specs(self, *, query: models.ListSpecsQuery | None = None, headers: Mapping[str, str] | None = None) -> models.SpecList: ...
    async def restore_spec(self, *, path: models.RestoreSpecPath, headers: Mapping[str, str] | None = None) -> models.MutationReceipt: ...
    async def set_issue_state(self, *, body: models.JsonValue | None = None, headers: Mapping[str, str] | None = None) -> models.MutationReceipt: ...
    async def update_feature(self, *, path: models.UpdateFeaturePath, body: models.FeaturePatch, headers: Mapping[str, str] | None = None) -> models.Feature: ...
    async def update_spec(self, *, path: models.UpdateSpecPath, body: models.SpecPatch, headers: Mapping[str, str] | None = None) -> models.Spec: ...
    async def upload_feature_attachment(self, *, path: models.UploadFeatureAttachmentPath, body: Mapping[str, Any], headers: Mapping[str, str] | None = None) -> models.SpecAttachment: ...
    async def upload_spec_attachment(self, *, path: models.UploadSpecAttachmentPath, body: Mapping[str, Any], headers: Mapping[str, str] | None = None) -> models.SpecAttachment: ...

class FeedbackClient(ResourceClient):
    def create_nox_spot_site(self, *, body: models.NoxSpotSiteCreate, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def delete_nox_spot_site(self, *, path: models.DeleteNoxSpotSitePath, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def get_nox_spot_project_overview(self, *, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def get_nox_spot_resolution_template(self, *, path: models.GetNoxSpotResolutionTemplatePath, headers: Mapping[str, str] | None = None) -> models.NoxSpotResolutionTemplateDocument: ...
    def get_public_nox_spot_config(self, *, path: models.GetPublicNoxSpotConfigPath, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def list_nox_spot_sites(self, *, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def preview_nox_spot_resolution_template(self, *, path: models.PreviewNoxSpotResolutionTemplatePath, body: models.PreviewNoxSpotResolutionTemplateBody, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def reopen_resolved_nox_spot_report(self, *, path: models.ReopenResolvedNoxSpotReportPath, body: Mapping[str, Any] | None = None, headers: Mapping[str, str] | None = None) -> str: ...
    def retry_nox_spot_deliveries(self, *, path: models.RetryNoxSpotDeliveriesPath, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def submit_public_nox_spot_errors(self, *, body: models.NoxSpotErrorBatch, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def submit_public_nox_spot_report(self, *, body: models.NoxSpotReport, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def test_nox_spot_resolution_template(self, *, path: models.TestNoxSpotResolutionTemplatePath, body: models.TestNoxSpotResolutionTemplateBody, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def update_nox_spot_report(self, *, path: models.UpdateNoxSpotReportPath, body: models.UpdateNoxSpotReportBody, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def update_nox_spot_resolution_template(self, *, path: models.UpdateNoxSpotResolutionTemplatePath, body: models.UpdateNoxSpotResolutionTemplateBody, headers: Mapping[str, str] | None = None) -> models.NoxSpotResolutionTemplateDocument: ...
    def update_nox_spot_site(self, *, path: models.UpdateNoxSpotSitePath, body: models.NoxSpotSitePatch, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...

class AsyncFeedbackClient(AsyncResourceClient):
    async def create_nox_spot_site(self, *, body: models.NoxSpotSiteCreate, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def delete_nox_spot_site(self, *, path: models.DeleteNoxSpotSitePath, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def get_nox_spot_project_overview(self, *, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def get_nox_spot_resolution_template(self, *, path: models.GetNoxSpotResolutionTemplatePath, headers: Mapping[str, str] | None = None) -> models.NoxSpotResolutionTemplateDocument: ...
    async def get_public_nox_spot_config(self, *, path: models.GetPublicNoxSpotConfigPath, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def list_nox_spot_sites(self, *, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def preview_nox_spot_resolution_template(self, *, path: models.PreviewNoxSpotResolutionTemplatePath, body: models.PreviewNoxSpotResolutionTemplateBody, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def reopen_resolved_nox_spot_report(self, *, path: models.ReopenResolvedNoxSpotReportPath, body: Mapping[str, Any] | None = None, headers: Mapping[str, str] | None = None) -> str: ...
    async def retry_nox_spot_deliveries(self, *, path: models.RetryNoxSpotDeliveriesPath, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def submit_public_nox_spot_errors(self, *, body: models.NoxSpotErrorBatch, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def submit_public_nox_spot_report(self, *, body: models.NoxSpotReport, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def test_nox_spot_resolution_template(self, *, path: models.TestNoxSpotResolutionTemplatePath, body: models.TestNoxSpotResolutionTemplateBody, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def update_nox_spot_report(self, *, path: models.UpdateNoxSpotReportPath, body: models.UpdateNoxSpotReportBody, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def update_nox_spot_resolution_template(self, *, path: models.UpdateNoxSpotResolutionTemplatePath, body: models.UpdateNoxSpotResolutionTemplateBody, headers: Mapping[str, str] | None = None) -> models.NoxSpotResolutionTemplateDocument: ...
    async def update_nox_spot_site(self, *, path: models.UpdateNoxSpotSitePath, body: models.NoxSpotSitePatch, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...

class IncidentsClient(ResourceClient):
    def create_nox_cue_custom_feature(self, *, path: models.CreateNoxCueCustomFeaturePath, body: models.NoxCueCustomFeatureInput, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def create_nox_cue_custom_metric(self, *, path: models.CreateNoxCueCustomMetricPath, body: models.NoxCueCustomMetricInput, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def create_nox_cue_key(self, *, path: models.CreateNoxCueKeyPath, body: models.CreateNoxCueKeyBody, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def create_nox_cue_source(self, *, body: models.NoxCueSourceInput, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def delete_nox_cue_custom_feature(self, *, path: models.DeleteNoxCueCustomFeaturePath, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def delete_nox_cue_custom_metric(self, *, path: models.DeleteNoxCueCustomMetricPath, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def delete_nox_cue_source(self, *, path: models.DeleteNoxCueSourcePath, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def get_cue_project_actions(self, *, path: models.GetCueProjectActionsPath, headers: Mapping[str, str] | None = None) -> models.ApiRecord: ...
    def get_cue_project_alert_rules(self, *, path: models.GetCueProjectAlertRulesPath, headers: Mapping[str, str] | None = None) -> models.ApiRecord: ...
    def get_cue_project_alerts(self, *, path: models.GetCueProjectAlertsPath, headers: Mapping[str, str] | None = None) -> models.ApiRecord: ...
    def get_cue_project_dashboard(self, *, path: models.GetCueProjectDashboardPath, headers: Mapping[str, str] | None = None) -> models.ApiRecord: ...
    def get_cue_project_stat_events(self, *, path: models.GetCueProjectStatEventsPath, headers: Mapping[str, str] | None = None) -> models.ApiRecord: ...
    def get_nox_cue_daily_health(self, *, query: models.GetNoxCueDailyHealthQuery, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def get_nox_cue_git_hub_issue_settings(self, *, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def get_nox_cue_project_metrics(self, *, path: models.GetNoxCueProjectMetricsPath, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def get_nox_cue_project_overview(self, *, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def ingest_nox_cue_event(self, *, body: JsonValue, headers: Mapping[str, str] | None = None) -> models.NoxCueIngestResponse: ...
    def list_nox_cue_cards(self, *, path: models.ListNoxCueCardsPath, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def list_nox_cue_custom_metrics(self, *, path: models.ListNoxCueCustomMetricsPath, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def list_nox_cue_events(self, *, query: models.ListNoxCueEventsQuery | None = None, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def list_nox_cue_features(self, *, path: models.ListNoxCueFeaturesPath, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def list_nox_cue_keys(self, *, path: models.ListNoxCueKeysPath, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def list_nox_cue_sources(self, *, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def put_nox_cue_git_hub_issue_settings(self, *, body: models.NoxCueGitHubIssueSettingsUpdate, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def revoke_nox_cue_key(self, *, path: models.RevokeNoxCueKeyPath, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def rotate_nox_cue_key(self, *, path: models.RotateNoxCueKeyPath, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def test_nox_cue_source(self, *, path: models.TestNoxCueSourcePath, body: models.JsonValue | None = None, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def update_cue_project_actions(self, *, path: models.UpdateCueProjectActionsPath, body: models.ApiRecord, headers: Mapping[str, str] | None = None) -> models.ApiRecord: ...
    def update_nox_cue_cards(self, *, path: models.UpdateNoxCueCardsPath, body: models.NoxCueCardSelection, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def update_nox_cue_custom_feature(self, *, path: models.UpdateNoxCueCustomFeaturePath, body: models.NoxCueCustomFeatureUpdate, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def update_nox_cue_custom_metric(self, *, path: models.UpdateNoxCueCustomMetricPath, body: models.NoxCueCustomMetricUpdate, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def update_nox_cue_error_status(self, *, path: models.UpdateNoxCueErrorStatusPath, body: models.UpdateNoxCueErrorStatusBody, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def update_nox_cue_project_metrics(self, *, path: models.UpdateNoxCueProjectMetricsPath, body: models.NoxCueProjectMetricSelection, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    def update_nox_cue_source(self, *, path: models.UpdateNoxCueSourcePath, body: models.NoxCueSourceInput, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...

class AsyncIncidentsClient(AsyncResourceClient):
    async def create_nox_cue_custom_feature(self, *, path: models.CreateNoxCueCustomFeaturePath, body: models.NoxCueCustomFeatureInput, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def create_nox_cue_custom_metric(self, *, path: models.CreateNoxCueCustomMetricPath, body: models.NoxCueCustomMetricInput, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def create_nox_cue_key(self, *, path: models.CreateNoxCueKeyPath, body: models.CreateNoxCueKeyBody, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def create_nox_cue_source(self, *, body: models.NoxCueSourceInput, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def delete_nox_cue_custom_feature(self, *, path: models.DeleteNoxCueCustomFeaturePath, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def delete_nox_cue_custom_metric(self, *, path: models.DeleteNoxCueCustomMetricPath, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def delete_nox_cue_source(self, *, path: models.DeleteNoxCueSourcePath, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def get_cue_project_actions(self, *, path: models.GetCueProjectActionsPath, headers: Mapping[str, str] | None = None) -> models.ApiRecord: ...
    async def get_cue_project_alert_rules(self, *, path: models.GetCueProjectAlertRulesPath, headers: Mapping[str, str] | None = None) -> models.ApiRecord: ...
    async def get_cue_project_alerts(self, *, path: models.GetCueProjectAlertsPath, headers: Mapping[str, str] | None = None) -> models.ApiRecord: ...
    async def get_cue_project_dashboard(self, *, path: models.GetCueProjectDashboardPath, headers: Mapping[str, str] | None = None) -> models.ApiRecord: ...
    async def get_cue_project_stat_events(self, *, path: models.GetCueProjectStatEventsPath, headers: Mapping[str, str] | None = None) -> models.ApiRecord: ...
    async def get_nox_cue_daily_health(self, *, query: models.GetNoxCueDailyHealthQuery, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def get_nox_cue_git_hub_issue_settings(self, *, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def get_nox_cue_project_metrics(self, *, path: models.GetNoxCueProjectMetricsPath, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def get_nox_cue_project_overview(self, *, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def ingest_nox_cue_event(self, *, body: JsonValue, headers: Mapping[str, str] | None = None) -> models.NoxCueIngestResponse: ...
    async def list_nox_cue_cards(self, *, path: models.ListNoxCueCardsPath, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def list_nox_cue_custom_metrics(self, *, path: models.ListNoxCueCustomMetricsPath, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def list_nox_cue_events(self, *, query: models.ListNoxCueEventsQuery | None = None, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def list_nox_cue_features(self, *, path: models.ListNoxCueFeaturesPath, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def list_nox_cue_keys(self, *, path: models.ListNoxCueKeysPath, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def list_nox_cue_sources(self, *, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def put_nox_cue_git_hub_issue_settings(self, *, body: models.NoxCueGitHubIssueSettingsUpdate, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def revoke_nox_cue_key(self, *, path: models.RevokeNoxCueKeyPath, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def rotate_nox_cue_key(self, *, path: models.RotateNoxCueKeyPath, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def test_nox_cue_source(self, *, path: models.TestNoxCueSourcePath, body: models.JsonValue | None = None, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def update_cue_project_actions(self, *, path: models.UpdateCueProjectActionsPath, body: models.ApiRecord, headers: Mapping[str, str] | None = None) -> models.ApiRecord: ...
    async def update_nox_cue_cards(self, *, path: models.UpdateNoxCueCardsPath, body: models.NoxCueCardSelection, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def update_nox_cue_custom_feature(self, *, path: models.UpdateNoxCueCustomFeaturePath, body: models.NoxCueCustomFeatureUpdate, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def update_nox_cue_custom_metric(self, *, path: models.UpdateNoxCueCustomMetricPath, body: models.NoxCueCustomMetricUpdate, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def update_nox_cue_error_status(self, *, path: models.UpdateNoxCueErrorStatusPath, body: models.UpdateNoxCueErrorStatusBody, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def update_nox_cue_project_metrics(self, *, path: models.UpdateNoxCueProjectMetricsPath, body: models.NoxCueProjectMetricSelection, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...
    async def update_nox_cue_source(self, *, path: models.UpdateNoxCueSourcePath, body: models.NoxCueSourceInput, headers: Mapping[str, str] | None = None) -> models.JsonValue: ...

class NoxHereClient:
    base_url: str
    workspace: WorkspaceClient
    activity: ActivityClient
    planning: PlanningClient
    feedback: FeedbackClient
    incidents: IncidentsClient
    connect: WorkspaceClient
    feed: ActivityClient
    ticket: PlanningClient
    spot: FeedbackClient
    cue: IncidentsClient
    def __init__(self, *, base_url: str = ..., token: str | None = ..., organization: str | None = ..., project_id: str | None = ..., csrf_token: str | None = ..., headers: Mapping[str, str] | None = ..., transport: Transport | None = ..., timeout: float = ..., max_retries: int = ..., retry_delay: float = ..., on_request: Callable[[Mapping[str, object]], None] | None = ..., on_response: Callable[[Mapping[str, object]], None] | None = ..., sleep: Callable[[float], None] = ...) -> None: ...
    def request(self, operation_id: str, *, path: Mapping[str, str | int] | None = ..., query: Mapping[str, str | int | float | bool | Sequence[str | int | float | bool] | None] | None = ..., body: JsonValue | str | bytes | None = ..., headers: Mapping[str, str] | None = ...) -> Any: ...
    def operation_ids(self) -> tuple[str, ...]: ...
    def with_context(self, *, organization: str | None = ..., project_id: str | None = ...) -> NoxHereClient: ...

class AsyncNoxHereClient:
    base_url: str
    workspace: AsyncWorkspaceClient
    activity: AsyncActivityClient
    planning: AsyncPlanningClient
    feedback: AsyncFeedbackClient
    incidents: AsyncIncidentsClient
    connect: AsyncWorkspaceClient
    feed: AsyncActivityClient
    ticket: AsyncPlanningClient
    spot: AsyncFeedbackClient
    cue: AsyncIncidentsClient
    def __init__(self, *, base_url: str = ..., token: str | None = ..., organization: str | None = ..., project_id: str | None = ..., csrf_token: str | None = ..., headers: Mapping[str, str] | None = ..., transport: Any = ..., timeout: float = ..., max_retries: int = ..., retry_delay: float = ..., on_request: Callable[[Mapping[str, object]], None] | None = ..., on_response: Callable[[Mapping[str, object]], None] | None = ...) -> None: ...
    async def request(self, operation_id: str, *, path: Mapping[str, str | int] | None = ..., query: Mapping[str, str | int | float | bool | Sequence[str | int | float | bool] | None] | None = ..., body: JsonValue | str | bytes | None = ..., headers: Mapping[str, str] | None = ...) -> Any: ...
    def operation_ids(self) -> tuple[str, ...]: ...
    def with_context(self, *, organization: str | None = ..., project_id: str | None = ...) -> AsyncNoxHereClient: ...

def create_noxhere(**options: Any) -> NoxHereClient: ...
def create_async_noxhere(**options: Any) -> AsyncNoxHereClient: ...
