# Generated by scripts/generate-sdk-contract.py. Do not edit.

CONTRACT_VERSION = 1
SDK_VERSION = '0.2.0'
__version__ = '0.2.0'
DEFAULT_ENDPOINT = 'https://app.noxhere.com/api/v1/cues/public/events'
AUTH_FEATURES = ('auth.signup', 'auth.login', 'auth.password_reset', 'auth.email_verification', 'auth.oauth', 'auth.mfa', 'auth.session_refresh', 'auth.logout')
ENVIRONMENTS = ('production', 'staging', 'development', 'preview', 'test', 'local')
OUTCOMES = ('success', 'rejected', 'failure')
REASONS = ('invalid_input', 'invalid_credentials', 'account_exists', 'account_unverified', 'account_locked', 'verification_expired', 'mfa_required', 'rate_limited', 'policy_rejected', 'dependency_unavailable', 'database_unavailable', 'email_delivery_failed', 'oauth_failed', 'session_failed', 'configuration_error', 'timeout', 'network_error', 'internal_error', 'unknown')
DELIVERY_ERRORS = ('invalid_configuration', 'payload_too_large', 'timeout', 'network_error', 'rejected')
DEFAULT_TIMEOUT_MS = 3000
MAX_TIMEOUT_MS = 10000
MAX_BODY_BYTES = 32768
MAX_RESPONSE_BYTES = 4096
RETRY_DELAY_MS = 250
MAX_RETRY_AFTER_MS = 1000
