// Generated by scripts/generate-sdk-contract.py. Do not edit.

export const CONTRACT_VERSION = 1 as const;
export const SDK_VERSION = "0.2.0" as const;
export const DEFAULT_ENDPOINT = "https://app.noxhere.com/api/v1/cues/public/events" as const;
export const NOXCUE_AUTH_FEATURES = ["auth.signup","auth.login","auth.password_reset","auth.email_verification","auth.oauth","auth.mfa","auth.session_refresh","auth.logout"] as const;
export const NOXCUE_ENVIRONMENTS = ["production","staging","development","preview","test","local"] as const;
export const NOXCUE_OUTCOMES = ["success","rejected","failure"] as const;
export const NOXCUE_REASONS = ["invalid_input","invalid_credentials","account_exists","account_unverified","account_locked","verification_expired","mfa_required","rate_limited","policy_rejected","dependency_unavailable","database_unavailable","email_delivery_failed","oauth_failed","session_failed","configuration_error","timeout","network_error","internal_error","unknown"] as const;
export const DELIVERY_ERRORS = ["invalid_configuration","payload_too_large","timeout","network_error","rejected"] as const;
export const DEFAULT_TIMEOUT_MS = 3000 as const;
export const MAX_TIMEOUT_MS = 10000 as const;
export const MAX_BODY_BYTES = 32768 as const;
export const MAX_RESPONSE_BYTES = 4096 as const;
export const RETRY_DELAY_MS = 250 as const;
export const MAX_RETRY_AFTER_MS = 1000 as const;
