-- Make the review workspace feel like an active, multi-repository team while
-- keeping every row deterministic and permanently read-only.

INSERT OR REPLACE INTO actors (id, name, github_login, avatar_url, kind) VALUES
  ('actor-jordan', 'Jordan Lee', 'jordan-demo', 'https://avatars.githubusercontent.com/u/583231?v=4', 'human'),
  ('actor-mei', 'Mei Chen', 'mei-demo', 'https://avatars.githubusercontent.com/u/69631?v=4', 'human');

INSERT OR REPLACE INTO members (login, avatar_url, kind, sort_order) VALUES
  ('jordan-demo', 'https://avatars.githubusercontent.com/u/583231?v=4', 'human', 4),
  ('mei-demo', 'https://avatars.githubusercontent.com/u/69631?v=4', 'human', 5);

INSERT OR REPLACE INTO projects (id, name, slug, org, repo, archived) VALUES
  ('project-auth', 'Identity Service', 'identity-service', 'NoxFeed-Demo', 'identity-service', 0),
  ('project-docs', 'Developer Docs', 'developer-docs', 'NoxFeed-Demo', 'developer-docs', 0);

INSERT OR REPLACE INTO pull_requests
  (id, repo, number, title, state, author, author_avatar, draft, head_ref, created_age_seconds, updated_age_seconds, html_url, merged_age_seconds, requested_reviewers_json)
VALUES
  (105, 'identity-service', 73, 'Rotate short-lived sessions without interrupting users', 'open', 'mei-demo', 'https://avatars.githubusercontent.com/u/69631?v=4', 0, 'feature/session-rotation', 345600, 2700, 'https://github.com/cloudflare/workers-sdk/pull/10000', NULL, '[{"login":"alex-demo"}]'),
  (106, 'team-dashboard', 58, 'Add repository health to the team overview', 'open', 'jordan-demo', 'https://avatars.githubusercontent.com/u/583231?v=4', 0, 'feature/repo-health', 129600, 5400, 'https://github.com/vercel/next.js/pull/79900', NULL, '[{"login":"reviewer-demo"},{"login":"priya-demo"}]'),
  (107, 'activity-api', 84, 'Batch webhook deliveries by installation', 'merged', 'priya-demo', 'https://avatars.githubusercontent.com/u/69631?v=4', 0, 'perf/webhook-batches', 604800, 75600, 'https://github.com/github/docs/pull/39900', 75600, '[{"login":"sam-demo"}]'),
  (108, 'noxfeed-macos', 130, 'Explore compact keyboard navigation', 'open', 'sam-demo', 'https://avatars.githubusercontent.com/u/810438?v=4', 1, 'prototype/keyboard-navigation', 64800, 9000, 'https://github.com/swiftlang/swift/pull/82600', NULL, '[]'),
  (109, 'developer-docs', 22, 'Document the organization rollout checklist', 'open', 'reviewer-demo', 'https://avatars.githubusercontent.com/u/583231?v=4', 0, 'docs/rollout-checklist', 93600, 12600, 'https://github.com/github/docs/pull/39800', NULL, '[{"login":"jordan-demo"}]');

INSERT OR REPLACE INTO issues
  (id, repo, number, title, state, author, author_avatar, created_age_seconds, updated_age_seconds, html_url, assignees_json, labels_json)
VALUES
  (204, 'identity-service', 68, 'Session expiry banner appears one minute too early', 'open', 'jordan-demo', 'https://avatars.githubusercontent.com/u/583231?v=4', 432000, 8100, 'https://github.com/cloudflare/workers-sdk/issues/11000', '["mei-demo"]', '["bug","authentication"]'),
  (205, 'developer-docs', 17, 'Add screenshots to the installation guide', 'open', 'mei-demo', 'https://avatars.githubusercontent.com/u/69631?v=4', 518400, 18000, 'https://github.com/github/docs/issues/38900', '["reviewer-demo","jordan-demo"]', '["documentation","good first issue"]'),
  (206, 'team-dashboard', 21, 'Repository filter should retain its selection', 'open', 'reviewer-demo', 'https://avatars.githubusercontent.com/u/583231?v=4', 259200, 25200, 'https://github.com/vercel/next.js/issues/78800', '["sam-demo"]', '["bug","state"]'),
  (207, 'activity-api', 35, 'Expose delivery latency in the health response', 'open', 'alex-demo', 'https://avatars.githubusercontent.com/u/9919?v=4', 388800, 39600, 'https://github.com/cloudflare/workers-sdk/issues/10900', '["alex-demo","priya-demo"]', '["observability","api"]');

INSERT OR REPLACE INTO events
  (id, type, feed_mode, source, actor_id, project_id, org, repo, pr_number, summary, age_seconds, payload_json)
VALUES
  (1300, 'pr_narrative', 'pr_narrative', 'github', 'actor-mei', 'project-auth', 'NoxFeed-Demo', 'identity-service', 73, 'I added seamless session rotation so active users keep working while credentials renew safely in the background.', 2700, '{"action":"opened","pr_number":73,"pr":{"number":73,"title":"Rotate short-lived sessions without interrupting users","html_url":"https://github.com/cloudflare/workers-sdk/pull/10000","author":"mei-demo","body":"Renews expiring sessions before they interrupt an active workspace.","head_ref":"feature/session-rotation","base_ref":"main","additions":184,"deletions":41,"changed_files":7,"draft":false}}'),
  (1299, 'pr_narrative', 'pr_narrative', 'github', 'actor-jordan', 'project-web', 'NoxFeed-Demo', 'team-dashboard', 58, 'I brought repository health into the team overview so maintainers can spot stalled reviews and aging pull requests at a glance.', 5400, '{"action":"opened","pr_number":58,"pr":{"number":58,"title":"Add repository health to the team overview","html_url":"https://github.com/vercel/next.js/pull/79900","author":"jordan-demo","body":"Adds compact repository health indicators to the existing workload view.","head_ref":"feature/repo-health","base_ref":"main","additions":312,"deletions":78,"changed_files":11,"draft":false}}'),
  (1298, 'narrative', 'narrative', 'github', 'actor-priya', 'project-api', 'NoxFeed-Demo', 'activity-api', 84, 'I batched webhook deliveries per installation, cutting duplicate work while preserving event order and retry safety.', 75600, '{"action":"closed","pr_number":84,"pr":{"number":84,"title":"Batch webhook deliveries by installation","html_url":"https://github.com/github/docs/pull/39900","author":"priya-demo","head_ref":"perf/webhook-batches","base_ref":"main","additions":267,"deletions":119,"changed_files":9}}'),
  (1297, 'narrative', 'narrative', 'github', 'actor-jordan', 'project-docs', 'NoxFeed-Demo', 'developer-docs', 20, 'I reorganized the installation guide around the decisions administrators actually make during a staged rollout.', 190800, '{"action":"closed","pr_number":20,"pr":{"number":20,"title":"Restructure the installation guide","html_url":"https://github.com/github/docs/pull/39700","author":"jordan-demo","head_ref":"docs/install-flow","base_ref":"main"}}'),
  (1296, 'release_notes', 'release_notes', 'github', 'actor-priya', 'project-api', 'NoxFeed-Demo', 'activity-api', 84, '✅ activity-api #84 Shipped - Performance\nRepository: activity-api\nPull Request: #84 - Batch webhook deliveries by installation\nAuthor: priya-demo | Merged by: priya-demo\nBranch: perf/webhook-batches → main\n\nChange Summary\nType: Performance\nDetails: Webhook deliveries are grouped by installation while ordering and retry behavior remain stable.\nBreaking Changes: None identified\nAffected Areas: ingestion, queues, delivery metrics\n\nRecommendations\nWatch delivery latency and retry volume during the first production hour.', 75600, '{"action":"closed","pr_number":84,"pr":{"number":84,"title":"Batch webhook deliveries by installation","html_url":"https://github.com/github/docs/pull/39900","author":"priya-demo","head_ref":"perf/webhook-batches","base_ref":"main"}}'),
  (1295, 'release_notes', 'release_notes', 'github', 'actor-jordan', 'project-docs', 'NoxFeed-Demo', 'developer-docs', 20, '✅ developer-docs #20 Shipped - Documentation\nRepository: developer-docs\nPull Request: #20 - Restructure the installation guide\nAuthor: jordan-demo | Merged by: jordan-demo\nBranch: docs/install-flow → main\n\nChange Summary\nType: Documentation\nDetails: The setup guide now follows a staged organization rollout from permissions through validation.\nBreaking Changes: None identified\nAffected Areas: installation guide, administrator checklist\n\nRecommendations\nValidate every link from a signed-out browser.', 190800, '{"action":"closed","pr_number":20,"pr":{"number":20,"title":"Restructure the installation guide","html_url":"https://github.com/github/docs/pull/39700","author":"jordan-demo","head_ref":"docs/install-flow","base_ref":"main"}}'),
  (1292, 'github:pr:opened', NULL, 'github', 'actor-mei', 'project-auth', 'NoxFeed-Demo', 'identity-service', 73, 'Rotate short-lived sessions without interrupting users', 345600, '{"action":"opened","pr":{"number":73,"title":"Rotate short-lived sessions without interrupting users","html_url":"https://github.com/cloudflare/workers-sdk/pull/10000","author":"mei-demo","body":"Renews expiring sessions before they interrupt an active workspace.","head_ref":"feature/session-rotation","base_ref":"main","additions":184,"deletions":41,"changed_files":7,"draft":false}}'),
  (1291, 'github:push', NULL, 'github', 'actor-mei', 'project-auth', 'NoxFeed-Demo', 'identity-service', 73, 'Handle rotation races during wake from sleep', 14400, '{"ref":"refs/heads/feature/session-rotation","pusher":"mei-demo","commits":[{"message":"Handle rotation races during wake from sleep"},{"message":"Add session renewal telemetry"}]}'),
  (1290, 'github:pr:review:approved', NULL, 'github', 'actor-alex', 'project-auth', 'NoxFeed-Demo', 'identity-service', 73, 'Approved session rotation', 2700, '{"action":"submitted","pr":{"number":73,"title":"Rotate short-lived sessions without interrupting users","html_url":"https://github.com/cloudflare/workers-sdk/pull/10000","author":"mei-demo"},"review":{"state":"approved","author":"alex-demo","body":"The wake-from-sleep race is covered and the fallback is safe."}}'),
  (1289, 'github:pr:opened', NULL, 'github', 'actor-jordan', 'project-web', 'NoxFeed-Demo', 'team-dashboard', 58, 'Add repository health to the team overview', 129600, '{"action":"opened","pr":{"number":58,"title":"Add repository health to the team overview","html_url":"https://github.com/vercel/next.js/pull/79900","author":"jordan-demo","body":"Adds compact repository health indicators to the existing workload view.","head_ref":"feature/repo-health","base_ref":"main","additions":312,"deletions":78,"changed_files":11,"draft":false}}'),
  (1288, 'github:pr:review:commented', NULL, 'github', 'actor-priya', 'project-web', 'NoxFeed-Demo', 'team-dashboard', 58, 'Requested a clearer stalled-review threshold', 5400, '{"action":"submitted","pr":{"number":58,"title":"Add repository health to the team overview","html_url":"https://github.com/vercel/next.js/pull/79900","author":"jordan-demo"},"review":{"state":"commented","author":"priya-demo","body":"Can we explain why a review is marked as stalled in the tooltip?"}}'),
  (1287, 'github:pr:opened', NULL, 'github', 'actor-priya', 'project-api', 'NoxFeed-Demo', 'activity-api', 84, 'Batch webhook deliveries by installation', 604800, '{"action":"opened","pr":{"number":84,"title":"Batch webhook deliveries by installation","html_url":"https://github.com/github/docs/pull/39900","author":"priya-demo","head_ref":"perf/webhook-batches","base_ref":"main","additions":267,"deletions":119,"changed_files":9,"draft":false}}'),
  (1286, 'github:push', NULL, 'github', 'actor-priya', 'project-api', 'NoxFeed-Demo', 'activity-api', 84, 'Preserve ordering across retry batches', 100800, '{"ref":"refs/heads/perf/webhook-batches","pusher":"priya-demo","commits":[{"message":"Preserve ordering across retry batches"}]}'),
  (1285, 'github:pr:review:approved', NULL, 'github', 'actor-sam', 'project-api', 'NoxFeed-Demo', 'activity-api', 84, 'Approved delivery batching', 79200, '{"action":"submitted","pr":{"number":84,"title":"Batch webhook deliveries by installation","html_url":"https://github.com/github/docs/pull/39900","author":"priya-demo"},"review":{"state":"approved","author":"sam-demo","body":"Ordering, retries, and observability all look solid."}}'),
  (1284, 'github:pr:merged', NULL, 'github', 'actor-priya', 'project-api', 'NoxFeed-Demo', 'activity-api', 84, 'Batch webhook deliveries by installation', 75600, '{"action":"closed","pr":{"number":84,"title":"Batch webhook deliveries by installation","html_url":"https://github.com/github/docs/pull/39900","author":"priya-demo","head_ref":"perf/webhook-batches","base_ref":"main","additions":267,"deletions":119,"changed_files":9}}');
